### ISSUE TITLE
epic: Offers Page Rewrite

### ISSUE THREAD

**Issue by davidtaing** [codesydney/migram-frontend#145]
Rewrite the Offers Page using Shopify's Polaris Design System.

## Existing Queries/Mutations

**Offers Dashboard**
No Queries

**Offers (List)**
- [x] Fetch Offers of Provider - `GET /api/v1/offers`
- [ ] ~~Fetch Task - `GET /api/v1/tasks/:taskId`~~ Edit: Nothing happens with this query. Good for removal.

**Offer**
- [x] Complete Task - `/api/v1/tasks/:taskId/completed`

## Screenshot - Old/Current Version
![image](https://user-images.githubusercontent.com/8443215/218011381-5d0f20a3-084d-4bc5-8d94-2b77c89580e8.png)
